"""create variant table

Revision ID: 12ed4ca79023
Revises: 35e637ba59bc
Create Date: 2022-12-01 21:21:30.977978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ed4ca79023'
down_revision = '35e637ba59bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant',
    sa.Column('variant_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('variant_name', sa.String(length=250), nullable=False),
    sa.Column('variant_size', sa.String(length=30), nullable=False),
    sa.Column('variant_metric', sa.String(length=10), nullable=True),
    sa.Column('variant_color', sa.String(length=30), nullable=True),
    sa.Column('logo_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('variant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant')
    # ### end Alembic commands ###
