"""new db

Revision ID: 1fbb05c3d060
Revises: 89caedc2b8fc
Create Date: 2022-12-03 22:49:26.673232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fbb05c3d060'
down_revision = '89caedc2b8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('image_name',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.LargeBinary(),
               nullable=True)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=150), nullable=False))
        batch_op.alter_column('image_name',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
