"""test

Revision ID: 2aa04a0e9e2b
Revises: f1e2ee19ece9
Create Date: 2022-12-02 17:42:57.080939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa04a0e9e2b'
down_revision = 'f1e2ee19ece9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
