"""create image table

Revision ID: 2fc3796965a9
Revises: 12ed4ca79023
Create Date: 2022-12-01 21:27:22.525512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc3796965a9'
down_revision = '12ed4ca79023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('image_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('image_name', sa.String(length=250), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
