"""a

Revision ID: 48b1ccd6e42e
Revises: 769e992a27fa
Create Date: 2022-12-03 23:16:35.075683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b1ccd6e42e'
down_revision = '769e992a27fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=150), nullable=True))

    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.drop_column('logo')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
