"""a

Revision ID: 769e992a27fa
Revises: 834267857ab2
Create Date: 2022-12-03 23:16:03.586254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769e992a27fa'
down_revision = '834267857ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=150), nullable=False))
        batch_op.drop_column('image')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('logo')

    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.BLOB(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.BLOB(), nullable=True))

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
