"""new db

Revision ID: 834267857ab2
Revises: 1fbb05c3d060
Create Date: 2022-12-03 22:52:27.294415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '834267857ab2'
down_revision = '1fbb05c3d060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('image_name',
               existing_type=sa.BLOB(),
               type_=sa.String(length=250),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('image_name',
               existing_type=sa.String(length=250),
               type_=sa.BLOB(),
               nullable=True)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
