"""change image storing system

Revision ID: 9363bef5a5c2
Revises: eee271dee35c
Create Date: 2022-12-02 11:50:20.693119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9363bef5a5c2'
down_revision = 'eee271dee35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=150), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
