"""input product id in variant table

Revision ID: eee271dee35c
Revises: 2fc3796965a9
Create Date: 2022-12-01 23:36:08.576413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee271dee35c'
down_revision = '2fc3796965a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
