"""add status column on every table

Revision ID: f1e2ee19ece9
Revises: 6c6e40f2b60f
Create Date: 2022-12-02 16:53:20.846346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e2ee19ece9'
down_revision = '6c6e40f2b60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
